### ISSUE TITLE
USER STORY: Customer registration

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#10]
As a **register an account** I can **register an account** so that **I can easily access my reservations**

## Acceptance criteria:
1. The website should have a place for the user register for an account;
2. When a customer makes a table reservation, should have a link that leads to the registration page;
3. The registration page is simple and easy to understand.

## Tasks:

- [ ] Create a registration page;
- [ ] Create a registration form;
- [ ] Send a email when the new costumer finish the registration with all the information provided;
- [ ] Test the functionality.
