### ISSUE TITLE
USER STORY: Customer account management

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#11]
As a **customer** I can **have an account** so that **I can consult, change or cancel my reservations**

## Acceptance criteria:
1. The customer account should have all the bookings made;
2. The customers can easily choose to consult, update or cancel their reservation;
3. The information is simple and easy to follow.

## Tasks:

- [ ] Create a consult option to reservations;
- [ ] Create a update option to reservations;
- [ ] Create a cancel option to reservations;
- [ ] Send a email to the customer with the new information;
- [ ] Update register client bookings;
- [ ] Test functionality.
