### ISSUE TITLE
USER STORY: Admin account - see customer new and update reservations

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#15]
As an **admin** I can **I can see when a customer has made a reservation or modified their reservation** so that **I can manage the restaurant booked tables more efficiently**

## Acceptance criteria:
1. The admin account should have all the reservations made;
2. The admin can consult all the reservations;
3. The admin can easily manage/update/cancel all reservations.

## Tasks:

- [ ]  If the customer made any changes: Update admin reservations view;
- [ ] If the customer made any changes: Update customer reservations view;
- [ ]  If the customer made any changes: Send a email to the admin email with the new information;
- [ ] Test functionality.
