### ISSUE TITLE
USER STORY: Contact

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#5]
As a **customer** I can **see how I can contact the restaurant** so that **I can communicate with the restaurant easily**

## Acceptance criteria:
1. The website could have a contact form;
2. The customers/users/visitors can easily send questions or ask for information;
3. The contact form is easy to complete.
4. It is not necessary to be registered on the site to fill in the form.
5. The contact form can also be an extra way for a registered customers to be able to contact the restaurant if they are having problems with their account.

## Tasks:

- [ ] Add a contact tab in the nav bar;
- [ ] Create a contact form;
- [ ] Add a text with additional contact information.
