### ISSUE TITLE
USER STORY: Customer booking - date and time

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#6]
As a **customer** I can **choose a date and time for a booking** so that **I can quickly book a table**

## Acceptance criteria:
1. The website must have booking system;
2. The customers can easily choose a date and time for their reservation;
3. The booking system is simple and easy to understand.

## Tasks:

- [ ] Add a reservation tab to nav bar;
- [ ] Add a book a table bottom in the main page;
- [ ] Create a date option for the costumer choose the day they want;
- [ ] Create a time option for the costumer choose the time they want;
- [ ] Create a booking system form;
- [ ] Send to the client a email with the booking confirmation;
- [ ] Update register client bookings.
