### ISSUE TITLE
USER STORY: Customer booking - confirmation

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/il-oro-dItalia-restaurant#9]
As a **customer** I can **receive an email with my booking details** so that **I can have a confirmation of my booking**

## Acceptance criteria:
1. The website must have a booking system;
2. The booking system is simple and easy to understand.
3. The customers should receive a by email a confirmation of their reservation;
4. The email have all the information given in the booking.

## Tasks:

- [ ] Create an template email;
- [ ] Add all the information input in the email by the costumer;
- [ ] Send to the client a email with the booking confirmation;
- [ ] Update register client bookings;
- [ ] Test the functionality.
